server:
  port: 10000
  servlet:
    session:
      tracking-modes: cookie
  ssl:
    enabled: true
    certificate: classpath:key/bideo+3.pem
    certificate-private-key: classpath:key/bideo+3-key.pem
spring:
  config:
    import:
      - optional:classpath:application-sol.yaml
      - optional:classpath:application-oauth.yaml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bideo?serverTimezone=Asia/Seoul
    username: bideo
    password: 1234
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 10MB
      max-file-size: 20MB
      max-request-size: 25MB
  data:
    redis:
      host: localhost
      port: 6379
  profiles:
    active: sol, oauth

  cache:
    type: redis

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.app.bideo.domain; com.app.bideo.dto;
  type-handlers-package: com.app.bideo.mybatis.handler
  configuration:
    map-underscore-to-camel-case: true

# openssl rand -base64 32
jwt:
  secret: r4jL/gqxy2Gb9oT/BNj0xsHiij2hiWKobnmgD9Hrw+c=